# Generated by Django 5.0.1 on 2024-01-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_alter_addcourse_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcourse',
            old_name='Name',
            new_name='Course_Title',
        ),
        migrations.RenameField(
            model_name='addcourse',
            old_name='brand',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='addcourse',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
